import React from "react"
import CIcon from '@coreui/icons-react'


const UserDashboard = () => {
  return <div>회원 dashboard</div>
}
const UserList = () => {
  return (
    <>
  <div>user list</div>
  <CIcon name="cil-crop" size="2xl" />
<CIcon name="cil-border-vertical" size="2xl" />
<CIcon name="cil-sort-alpha-up" size="2xl" />
<CIcon name="cil-clear-all" size="2xl" />
<CIcon name="cil-print" size="2xl" />
<CIcon name="cil-football" size="2xl" />
<CIcon name="cil-signal-cellular-4" size="2xl" />
<CIcon name="cil-border-top" size="2xl" />
<CIcon name="cil-storage" size="2xl" />
<CIcon name="cil-heart" size="2xl" />
<CIcon name="cil-filter-photo" size="2xl" />
<CIcon name="cil-link-alt" size="2xl" />
<CIcon name="cil-speech" size="2xl" />
<CIcon name="cil-3d" size="2xl" />
<CIcon name="cil-language" size="2xl" />
<CIcon name="cil-square" size="2xl" />
<CIcon name="cil-hdr" size="2xl" />
<CIcon name="cil-blur" size="2xl" />
<CIcon name="cil-hd" size="2xl" />
<CIcon name="cil-vertical-align-bottom" size="2xl" />
<CIcon name="cil-room" size="2xl" />
<CIcon name="cil-spa" size="2xl" />
<CIcon name="cil-graph" size="2xl" />
<CIcon name="cil-baseball" size="2xl" />
<CIcon name="cil-cat" size="2xl" />
<CIcon name="cil-apple" size="2xl" />
<CIcon name="cil-mood-very-good" size="2xl" />
<CIcon name="cil-mouse" size="2xl" />
<CIcon name="cil-face-dead" size="2xl" />
<CIcon name="cil-resize-both" size="2xl" />
<CIcon name="cil-arrow-thick-from-top" size="2xl" />
<CIcon name="cil-animal" size="2xl" />
<CIcon name="cil-color-palette" size="2xl" />
<CIcon name="cil-minus" size="2xl" />
<CIcon name="cil-highligt" size="2xl" />
<CIcon name="cil-strikethrough" size="2xl" />
<CIcon name="cil-videogame" size="2xl" />
<CIcon name="cil-camera" size="2xl" />
<CIcon name="cil-wrap-text" size="2xl" />
<CIcon name="cil-arrow-circle-right" size="2xl" />
<CIcon name="cil-alarm" size="2xl" />
<CIcon name="cil-resize-width" size="2xl" />
<CIcon name="cil-thumb-down" size="2xl" />
<CIcon name="cil-people" size="2xl" />
<CIcon name="cil-calendar" size="2xl" />
<CIcon name="cil-mood-very-bad" size="2xl" />
<CIcon name="cil-diamond" size="2xl" />
<CIcon name="cil-eco" size="2xl" />
<CIcon name="cil-command" size="2xl" />
<CIcon name="cil-justify-left" size="2xl" />
<CIcon name="cil-sitemap" size="2xl" />
<CIcon name="cil-ethernet" size="2xl" />
<CIcon name="cil-audio-spectrum" size="2xl" />
<CIcon name="cil-scrubber" size="2xl" />
<CIcon name="cil-reload" size="2xl" />
<CIcon name="cil-burger" size="2xl" />
<CIcon name="cil-audio-description" size="2xl" />
<CIcon name="cil-move" size="2xl" />
<CIcon name="cil-garage" size="2xl" />
<CIcon name="cil-bike" size="2xl" />
<CIcon name="cil-chat-bubble" size="2xl" />
<CIcon name="cil-smile-plus" size="2xl" />
<CIcon name="cil-media-skip-forward" size="2xl" />
<CIcon name="cil-file" size="2xl" />
<CIcon name="cil-options" size="2xl" />
<CIcon name="cil-screen-smartphone" size="2xl" />
<CIcon name="cil-border-outer" size="2xl" />
<CIcon name="cil-spreadsheet" size="2xl" />
<CIcon name="cil-power-standby" size="2xl" />
<CIcon name="cil-smoking-room" size="2xl" />
<CIcon name="cil-media-pause" size="2xl" />
<CIcon name="cil-asterisk" size="2xl" />
<CIcon name="cil-rowing" size="2xl" />
<CIcon name="cil-border-clear" size="2xl" />
<CIcon name="cil-drink-alcohol" size="2xl" />
<CIcon name="cil-exposure" size="2xl" />
<CIcon name="cil-bookmark" size="2xl" />
<CIcon name="cil-swap-horizontal" size="2xl" />
<CIcon name="cil-cloud" size="2xl" />
<CIcon name="cil-caret-top" size="2xl" />
<CIcon name="cil-history" size="2xl" />
<CIcon name="cil-lock-locked" size="2xl" />
<CIcon name="cil-monitor" size="2xl" />
<CIcon name="cil-gamepad" size="2xl" />
<CIcon name="cil-loop-1" size="2xl" />
<CIcon name="cil-video" size="2xl" />
<CIcon name="cil-wheelchair" size="2xl" />
<CIcon name="cil-check-alt" size="2xl" />
<CIcon name="cil-data-transfer-down" size="2xl" />
<CIcon name="cil-media-step-forward" size="2xl" />
<CIcon name="cil-playlist-add" size="2xl" />
<CIcon name="cil-list" size="2xl" />
<CIcon name="cil-album" size="2xl" />
<CIcon name="cil-tennis-ball" size="2xl" />
<CIcon name="cil-color-border" size="2xl" />
<CIcon name="cil-money" size="2xl" />
<CIcon name="cil-double-quote-sans-left" size="2xl" />
<CIcon name="cil-satelite" size="2xl" />
<CIcon name="cil-swimming" size="2xl" />
<CIcon name="cil-arrow-thick-to-right" size="2xl" />
<CIcon name="cil-signal-cellular-3" size="2xl" />
<CIcon name="cil-grid" size="2xl" />
<CIcon name="cil-elevator" size="2xl" />
<CIcon name="cil-chevron-double-left" size="2xl" />
<CIcon name="cil-task" size="2xl" />
<CIcon name="cil-pushchair" size="2xl" />
<CIcon name="cil-pencil" size="2xl" />
<CIcon name="cil-pool" size="2xl" />
<CIcon name="cil-arrow-circle-bottom" size="2xl" />
<CIcon name="cil-backspace" size="2xl" />
<CIcon name="cil-double-quote-sans-right" size="2xl" />
<CIcon name="cil-bell-exclamation" size="2xl" />
<CIcon name="cil-comment-bubble" size="2xl" />
<CIcon name="cil-home" size="2xl" />
<CIcon name="cil-voice-over-record" size="2xl" />
<CIcon name="cil-wifi-signal-off" size="2xl" />
<CIcon name="cil-share" size="2xl" />
<CIcon name="cil-braille" size="2xl" />
<CIcon name="cil-airplane-mode-off" size="2xl" />
<CIcon name="cil-building" size="2xl" />
<CIcon name="cil-user" size="2xl" />
<CIcon name="cil-grain" size="2xl" />
<CIcon name="cil-list-numbered" size="2xl" />
<CIcon name="cil-cut" size="2xl" />
<CIcon name="cil-input-power" size="2xl" />
<CIcon name="cil-clock" size="2xl" />
<CIcon name="cil-action-redo" size="2xl" />
<CIcon name="cil-closed-captioning" size="2xl" />
<CIcon name="cil-hand-point-left" size="2xl" />
<CIcon name="cil-toilet" size="2xl" />
<CIcon name="cil-audio" size="2xl" />
<CIcon name="cil-disabled" size="2xl" />
<CIcon name="cil-car-alt" size="2xl" />
<CIcon name="cil-memory" size="2xl" />
<CIcon name="cil-face" size="2xl" />
<CIcon name="cil-report-slash" size="2xl" />
<CIcon name="cil-signal-cellular-0" size="2xl" />
<CIcon name="cil-list-numbered-rtl" size="2xl" />
<CIcon name="cil-location-pin" size="2xl" />
<CIcon name="cil-object-group" size="2xl" />
<CIcon name="cil-smoke" size="2xl" />
<CIcon name="cil-yen" size="2xl" />
<CIcon name="cil-american-football" size="2xl" />
<CIcon name="cil-phone" size="2xl" />
<CIcon name="cil-chevron-top" size="2xl" />
<CIcon name="cil-caret-left" size="2xl" />
<CIcon name="cil-gem" size="2xl" />
<CIcon name="cil-medical-cross" size="2xl" />
<CIcon name="cil-volume-low" size="2xl" />
<CIcon name="cil-wifi-signal-0" size="2xl" />
<CIcon name="cil-lan" size="2xl" />
<CIcon name="cil-code" size="2xl" />
<CIcon name="cil-arrow-left" size="2xl" />
<CIcon name="cil-pregnant" size="2xl" />
<CIcon name="cil-chevron-double-up" size="2xl" />
<CIcon name="cil-filter" size="2xl" />
<CIcon name="cil-level-down" size="2xl" />
<CIcon name="cil-cast" size="2xl" />
<CIcon name="cil-input" size="2xl" />
<CIcon name="cil-italic" size="2xl" />
<CIcon name="cil-functions-alt" size="2xl" />
<CIcon name="cil-border-inner" size="2xl" />
<CIcon name="cil-sun" size="2xl" />
<CIcon name="cil-object-ungroup" size="2xl" />
<CIcon name="cil-brush-alt" size="2xl" />
<CIcon name="cil-laptop" size="2xl" />
<CIcon name="cil-bolt-circle" size="2xl" />
<CIcon name="cil-pizza" size="2xl" />
<CIcon name="cil-bell" size="2xl" />
<CIcon name="cil-barcode" size="2xl" />
<CIcon name="cil-media-play" size="2xl" />
<CIcon name="cil-applications-settings" size="2xl" />
<CIcon name="cil-x" size="2xl" />
<CIcon name="cil-paperclip" size="2xl" />
<CIcon name="cil-wifi-signal-1" size="2xl" />
<CIcon name="cil-speaker" size="2xl" />
<CIcon name="cil-fullscreen-exit" size="2xl" />
<CIcon name="cil-lemon" size="2xl" />
<CIcon name="cil-taxi" size="2xl" />
<CIcon name="cil-book" size="2xl" />
<CIcon name="cil-text-square" size="2xl" />
<CIcon name="cil-share-all" size="2xl" />
<CIcon name="cil-industry" size="2xl" />
<CIcon name="cil-opentype" size="2xl" />
<CIcon name="cil-info" size="2xl" />
<CIcon name="cil-dialpad" size="2xl" />
<CIcon name="cil-arrow-thick-from-left" size="2xl" />
<CIcon name="cil-bug" size="2xl" />
<CIcon name="cil-camera-control" size="2xl" />
<CIcon name="cil-zoom-out" size="2xl" />
<CIcon name="cil-caret-right" size="2xl" />
<CIcon name="cil-wifi-signal-3" size="2xl" />
<CIcon name="cil-input-hdmi" size="2xl" />
<CIcon name="cil-delete" size="2xl" />
<CIcon name="cil-router" size="2xl" />
<CIcon name="cil-trash" size="2xl" />
<CIcon name="cil-arrow-thick-to-top" size="2xl" />
<CIcon name="cil-zoom-in" size="2xl" />
<CIcon name="cil-mobile-landscape" size="2xl" />
<CIcon name="cil-cloud-upload" size="2xl" />
<CIcon name="cil-cc" size="2xl" />
<CIcon name="cil-lightbulb" size="2xl" />
<CIcon name="cil-boat-alt" size="2xl" />
<CIcon name="cil-plus" size="2xl" />
<CIcon name="cil-mobile" size="2xl" />
<CIcon name="cil-opacity" size="2xl" />
<CIcon name="cil-voice" size="2xl" />
<CIcon name="cil-arrow-thick-from-bottom" size="2xl" />
<CIcon name="cil-industry-slash" size="2xl" />
<CIcon name="cil-flower" size="2xl" />
<CIcon name="cil-truck" size="2xl" />
<CIcon name="cil-chevron-circle-up-alt" size="2xl" />
<CIcon name="cil-envelope-open" size="2xl" />
<CIcon name="cil-speedometer" size="2xl" />
<CIcon name="cil-wifi-signal-2" size="2xl" />
<CIcon name="cil-sort-numeric-down" size="2xl" />
<CIcon name="cil-bold" size="2xl" />
<CIcon name="cil-basketball" size="2xl" />
<CIcon name="cil-smoke-free" size="2xl" />
<CIcon name="cil-line-weight" size="2xl" />
<CIcon name="cil-swap-vertical" size="2xl" />
<CIcon name="cil-filter-x" size="2xl" />
<CIcon name="cil-chevron-right" size="2xl" />
<CIcon name="cil-infinity" size="2xl" />
<CIcon name="cil-align-left" size="2xl" />
<CIcon name="cil-bus-alt" size="2xl" />
<CIcon name="cil-birthday-cake" size="2xl" />
<CIcon name="cil-mouth-slash" size="2xl" />
<CIcon name="cil-browser" size="2xl" />
<CIcon name="cil-zoom" size="2xl" />
<CIcon name="cil-folder-open" size="2xl" />
<CIcon name="cil-magnifying-glass" size="2xl" />
<CIcon name="cil-mic" size="2xl" />
<CIcon name="cil-image-broken" size="2xl" />
<CIcon name="cil-sort-numeric-up" size="2xl" />
<CIcon name="cil-folder" size="2xl" />
<CIcon name="cil-wc" size="2xl" />
<CIcon name="cil-basket" size="2xl" />
<CIcon name="cil-border-horizontal" size="2xl" />
<CIcon name="cil-equalizer" size="2xl" />
<CIcon name="cil-battery-full" size="2xl" />
<CIcon name="cil-euro" size="2xl" />
<CIcon name="cil-link" size="2xl" />
<CIcon name="cil-chart-pie" size="2xl" />
<CIcon name="cil-fire" size="2xl" />
<CIcon name="cil-find-in-page" size="2xl" />
<CIcon name="cil-education" size="2xl" />
<CIcon name="cil-badge" size="2xl" />
<CIcon name="cil-compass" size="2xl" />
<CIcon name="cil-chevron-double-right" size="2xl" />
<CIcon name="cil-arrow-right" size="2xl" />
<CIcon name="cil-bath" size="2xl" />
<CIcon name="cil-user-female" size="2xl" />
<CIcon name="cil-account-logout" size="2xl" />
<CIcon name="cil-window" size="2xl" />
<CIcon name="cil-bolt" size="2xl" />
<CIcon name="cil-image" size="2xl" />
<CIcon name="cil-brightness" size="2xl" />
<CIcon name="cil-child" size="2xl" />
<CIcon name="cil-view-stream" size="2xl" />
<CIcon name="cil-data-transfer-up" size="2xl" />
<CIcon name="cil-calculator" size="2xl" />
<CIcon name="cil-child-friendly" size="2xl" />
<CIcon name="cil-cloudy" size="2xl" />
<CIcon name="cil-action-undo" size="2xl" />
<CIcon name="cil-hand-point-up" size="2xl" />
<CIcon name="cil-apps" size="2xl" />
<CIcon name="cil-tablet" size="2xl" />
<CIcon name="cil-smile" size="2xl" />
<CIcon name="cil-cart" size="2xl" />
<CIcon name="cil-mood-bad" size="2xl" />
<CIcon name="cil-running" size="2xl" />
<CIcon name="cil-sort-descending" size="2xl" />
<CIcon name="cil-calendar-check" size="2xl" />
<CIcon name="cil-wifi-signal-4" size="2xl" />
<CIcon name="cil-header" size="2xl" />
<CIcon name="cil-fridge" size="2xl" />
<CIcon name="cil-expand-left" size="2xl" />
<CIcon name="cil-mug-tea" size="2xl" />
<CIcon name="cil-happy" size="2xl" />
<CIcon name="cil-star" size="2xl" />
<CIcon name="cil-watch" size="2xl" />
<CIcon name="cil-media-skip-backward" size="2xl" />
<CIcon name="cil-user-plus" size="2xl" />
<CIcon name="cil-leaf" size="2xl" />
<CIcon name="cil-keyboard" size="2xl" />
<CIcon name="cil-fullscreen" size="2xl" />
<CIcon name="cil-resize-height" size="2xl" />
<CIcon name="cil-restaurant" size="2xl" />
<CIcon name="cil-aperture" size="2xl" />
<CIcon name="cil-share-boxed" size="2xl" />
<CIcon name="cil-4k" size="2xl" />
<CIcon name="cil-battery-5" size="2xl" />
<CIcon name="cil-weightlifitng" size="2xl" />
<CIcon name="cil-tv" size="2xl" />
<CIcon name="cil-indent-decrease" size="2xl" />
<CIcon name="cil-caret-bottom" size="2xl" />
<CIcon name="cil-wallpaper" size="2xl" />
<CIcon name="cil-library-building" size="2xl" />
<CIcon name="cil-expand-up" size="2xl" />
<CIcon name="cil-border-style" size="2xl" />
<CIcon name="cil-dollar" size="2xl" />
<CIcon name="cil-circle" size="2xl" />
<CIcon name="cil-loop" size="2xl" />
<CIcon name="cil-camera-roll" size="2xl" />
<CIcon name="cil-crop-rotate" size="2xl" />
<CIcon name="cil-golf-alt" size="2xl" />
<CIcon name="cil-flip-to-back" size="2xl" />
<CIcon name="cil-gif" size="2xl" />
<CIcon name="cil-smoke-slash" size="2xl" />
<CIcon name="cil-check" size="2xl" />
<CIcon name="cil-lock-unlocked" size="2xl" />
<CIcon name="cil-hamburger-menu" size="2xl" />
<CIcon name="cil-highlighter" size="2xl" />
<CIcon name="cil-bank" size="2xl" />
<CIcon name="cil-soccer" size="2xl" />
<CIcon name="cil-search" size="2xl" />
<CIcon name="cil-compress" size="2xl" />
<CIcon name="cil-user-unfollow" size="2xl" />
<CIcon name="cil-qr-code" size="2xl" />
<CIcon name="cil-plant" size="2xl" />
<CIcon name="cil-settings" size="2xl" />
<CIcon name="cil-frown" size="2xl" />
<CIcon name="cil-border-right" size="2xl" />
<CIcon name="cil-clipboard" size="2xl" />
<CIcon name="cil-volume-high" size="2xl" />
<CIcon name="cil-view-module" size="2xl" />
<CIcon name="cil-life-ring" size="2xl" />
<CIcon name="cil-fax" size="2xl" />
<CIcon name="cil-vertical-align-top" size="2xl" />
<CIcon name="cil-dinner" size="2xl" />
<CIcon name="cil-stream" size="2xl" />
<CIcon name="cil-chart-line" size="2xl" />
<CIcon name="cil-at" size="2xl" />
<CIcon name="cil-tennis" size="2xl" />
<CIcon name="cil-cash" size="2xl" />
<CIcon name="cil-airplane-mode" size="2xl" />
<CIcon name="cil-border-left" size="2xl" />
<CIcon name="cil-hot-tub" size="2xl" />
<CIcon name="cil-comment-square" size="2xl" />
<CIcon name="cil-dog" size="2xl" />
<CIcon name="cil-expand-right" size="2xl" />
<CIcon name="cil-volume-off" size="2xl" />
<CIcon name="cil-justify-center" size="2xl" />
<CIcon name="cil-bar-chart" size="2xl" />
<CIcon name="cil-media-step-backward" size="2xl" />
<CIcon name="cil-hand-point-right" size="2xl" />
<CIcon name="cil-check-circle" size="2xl" />
<CIcon name="cil-rss" size="2xl" />
<CIcon name="cil-healing" size="2xl" />
<CIcon name="cil-credit-card" size="2xl" />
<CIcon name="cil-save" size="2xl" />
<CIcon name="cil-flag-alt" size="2xl" />
<CIcon name="cil-locomotive" size="2xl" />
<CIcon name="cil-british-pound" size="2xl" />
<CIcon name="cil-fork" size="2xl" />
<CIcon name="cil-ban" size="2xl" />
<CIcon name="cil-expand-down" size="2xl" />
<CIcon name="cil-link-broken" size="2xl" />
<CIcon name="cil-factory" size="2xl" />
<CIcon name="cil-warning" size="2xl" />
<CIcon name="cil-note-add" size="2xl" />
<CIcon name="cil-functions" size="2xl" />
<CIcon name="cil-bowling" size="2xl" />
<CIcon name="cil-center-focus" size="2xl" />
<CIcon name="cil-text" size="2xl" />
<CIcon name="cil-indent-increase" size="2xl" />
<CIcon name="cil-puzzle" size="2xl" />
<CIcon name="cil-assistive-listening-system" size="2xl" />
<CIcon name="cil-text-size" size="2xl" />
<CIcon name="cil-copy" size="2xl" />
<CIcon name="cil-justify-right" size="2xl" />
<CIcon name="cil-rain" size="2xl" />
<CIcon name="cil-screen-desktop" size="2xl" />
<CIcon name="cil-battery-3" size="2xl" />
<CIcon name="cil-align-right" size="2xl" />
<CIcon name="cil-chevron-circle-down-alt" size="2xl" />
<CIcon name="cil-group" size="2xl" />
<CIcon name="cil-burn" size="2xl" />
<CIcon name="cil-applications" size="2xl" />
<CIcon name="cil-meh" size="2xl" />
<CIcon name="cil-sad" size="2xl" />
<CIcon name="cil-battery-alert" size="2xl" />
<CIcon name="cil-bluetooth" size="2xl" />
<CIcon name="cil-text-strike" size="2xl" />
<CIcon name="cil-asterisk-circle" size="2xl" />
<CIcon name="cil-movie" size="2xl" />
<CIcon name="cil-window-minimize" size="2xl" />
<CIcon name="cil-microphone" size="2xl" />
<CIcon name="cil-share-alt" size="2xl" />
<CIcon name="cil-beach-access" size="2xl" />
<CIcon name="cil-pen" size="2xl" />
<CIcon name="cil-list-rich" size="2xl" />
<CIcon name="cil-blur-linear" size="2xl" />
<CIcon name="cil-gradient" size="2xl" />
<CIcon name="cil-snowflake" size="2xl" />
<CIcon name="cil-speak" size="2xl" />
<CIcon name="cil-hospital" size="2xl" />
<CIcon name="cil-newspaper" size="2xl" />
<CIcon name="cil-arrow-bottom" size="2xl" />
<CIcon name="cil-baby" size="2xl" />
<CIcon name="cil-loop-circular" size="2xl" />
<CIcon name="cil-star-half" size="2xl" />
<CIcon name="cil-terrain" size="2xl" />
<CIcon name="cil-color-fill" size="2xl" />
<CIcon name="cil-level-up" size="2xl" />
<CIcon name="cil-paper-plane" size="2xl" />
<CIcon name="cil-brush" size="2xl" />
<CIcon name="cil-battery-empty" size="2xl" />
<CIcon name="cil-send" size="2xl" />
<CIcon name="cil-chevron-circle-left-alt" size="2xl" />
<CIcon name="cil-golf" size="2xl" />
<CIcon name="cil-media-stop" size="2xl" />
<CIcon name="cil-paragraph" size="2xl" />
<CIcon name="cil-arrow-top" size="2xl" />
<CIcon name="cil-media-record" size="2xl" />
<CIcon name="cil-filter-frames" size="2xl" />
<CIcon name="cil-battery-0" size="2xl" />
<CIcon name="cil-text-shapes" size="2xl" />
<CIcon name="cil-address-book" size="2xl" />
<CIcon name="cil-bullhorn" size="2xl" />
<CIcon name="cil-baby-carriage" size="2xl" />
<CIcon name="cil-line-spacing" size="2xl" />
<CIcon name="cil-arrow-thick-from-right" size="2xl" />
<CIcon name="cil-cursor-move" size="2xl" />
<CIcon name="cil-pin" size="2xl" />
<CIcon name="cil-vector" size="2xl" />
<CIcon name="cil-low-vision" size="2xl" />
<CIcon name="cil-shower" size="2xl" />
<CIcon name="cil-drop" size="2xl" />
<CIcon name="cil-menu" size="2xl" />
<CIcon name="cil-pen-nib" size="2xl" />
<CIcon name="cil-arrow-thick-left" size="2xl" />
<CIcon name="cil-arrow-thick-to-bottom" size="2xl" />
<CIcon name="cil-space-bar" size="2xl" />
<CIcon name="cil-user-follow" size="2xl" />
<CIcon name="cil-rectangle" size="2xl" />
<CIcon name="cil-window-restore" size="2xl" />
<CIcon name="cil-globe-alt" size="2xl" />
<CIcon name="cil-sort-ascending" size="2xl" />
<CIcon name="cil-window-maximize" size="2xl" />
<CIcon name="cil-ruble" size="2xl" />
<CIcon name="cil-cloud-download" size="2xl" />
<CIcon name="cil-envelope-letter" size="2xl" />
<CIcon name="cil-arrow-thick-bottom" size="2xl" />
<CIcon name="cil-exit-to-app" size="2xl" />
<CIcon name="cil-triangle" size="2xl" />
<CIcon name="cil-short-text" size="2xl" />
<CIcon name="cil-transfer" size="2xl" />
<CIcon name="cil-school" size="2xl" />
<CIcon name="cil-flip-to-front" size="2xl" />
<CIcon name="cil-flip" size="2xl" />
<CIcon name="cil-inbox" size="2xl" />
<CIcon name="cil-paint" size="2xl" />
<CIcon name="cil-institution" size="2xl" />
<CIcon name="cil-list-high-priority" size="2xl" />
<CIcon name="cil-envelope-closed" size="2xl" />
<CIcon name="cil-list-low-priority" size="2xl" />
<CIcon name="cil-align-center" size="2xl" />
<CIcon name="cil-translate" size="2xl" />
<CIcon name="cil-tag" size="2xl" />
<CIcon name="cil-bathroom" size="2xl" />
<CIcon name="cil-grid-slash" size="2xl" />
<CIcon name="cil-touch-app" size="2xl" />
<CIcon name="cil-border-all" size="2xl" />
<CIcon name="cil-usb" size="2xl" />
<CIcon name="cil-walk" size="2xl" />
<CIcon name="cil-couch" size="2xl" />
<CIcon name="cil-thumb-up" size="2xl" />
<CIcon name="cil-factory-slash" size="2xl" />
<CIcon name="cil-library-add" size="2xl" />
<CIcon name="cil-columns" size="2xl" />
<CIcon name="cil-sort-alpha-down" size="2xl" />
<CIcon name="cil-list-filter" size="2xl" />
<CIcon name="cil-chevron-bottom" size="2xl" />
<CIcon name="cil-arrow-circle-left" size="2xl" />
<CIcon name="cil-sofa" size="2xl" />
<CIcon name="cil-contact" size="2xl" />
<CIcon name="cil-font" size="2xl" />
<CIcon name="cil-map" size="2xl" />
<CIcon name="cil-moon" size="2xl" />
<CIcon name="cil-fingerprint" size="2xl" />
<CIcon name="cil-line-style" size="2xl" />
<CIcon name="cil-toggle-off" size="2xl" />
<CIcon name="cil-arrow-thick-right" size="2xl" />
<CIcon name="cil-pen-alt" size="2xl" />
<CIcon name="cil-view-column" size="2xl" />
<CIcon name="cil-chevron-circle-right-alt" size="2xl" />
<CIcon name="cil-underline" size="2xl" />
<CIcon name="cil-excerpt" size="2xl" />
<CIcon name="cil-x-circle" size="2xl" />
<CIcon name="cil-featured-playlist" size="2xl" />
<CIcon name="cil-beaker" size="2xl" />
<CIcon name="cil-toggle-on" size="2xl" />
<CIcon name="cil-mood-good" size="2xl" />
<CIcon name="cil-paw" size="2xl" />
<CIcon name="cil-view-quilt" size="2xl" />
<CIcon name="cil-airplay" size="2xl" />
<CIcon name="cil-media-eject" size="2xl" />
<CIcon name="cil-gift" size="2xl" />
<CIcon name="cil-cursor" size="2xl" />
<CIcon name="cil-blur-circular" size="2xl" />
<CIcon name="cil-blind" size="2xl" />
<CIcon name="cil-arrow-thick-top" size="2xl" />
<CIcon name="cil-hand-point-down" size="2xl" />
<CIcon name="cil-headphones" size="2xl" />
<CIcon name="cil-external-link" size="2xl" />
<CIcon name="cil-sim" size="2xl" />
<CIcon name="cil-fastfood" size="2xl" />
<CIcon name="cil-mug" size="2xl" />
<CIcon name="cil-flight-takeoff" size="2xl" />
<CIcon name="cil-control" size="2xl" />
<CIcon name="cil-chart" size="2xl" />
<CIcon name="cil-music-note" size="2xl" />
<CIcon name="cil-devices" size="2xl" />
<CIcon name="cil-battery-slash" size="2xl" />
<CIcon name="cil-cog" size="2xl" />
<CIcon name="cil-sync" size="2xl" />
<CIcon name="cil-chevron-left" size="2xl" />
<CIcon name="cil-paint-bucket" size="2xl" />
<CIcon name="cil-bed" size="2xl" />
<CIcon name="cil-user-x" size="2xl" />
<CIcon name="cil-deaf" size="2xl" />
<CIcon name="cil-vertical-align-center" size="2xl" />
<CIcon name="cil-briefcase" size="2xl" />
<CIcon name="cil-layers" size="2xl" />
<CIcon name="cil-library" size="2xl" />
<CIcon name="cil-house" size="2xl" />
<CIcon name="cil-recycle" size="2xl" />
<CIcon name="cil-sign-language" size="2xl" />
<CIcon name="cil-chevron-double-down" size="2xl" />
<CIcon name="cil-image-plus" size="2xl" />
<CIcon name="cil-shield-alt" size="2xl" />
<CIcon name="cil-wallet" size="2xl" />
<CIcon name="cil-description" size="2xl" />
<CIcon name="cil-casino" size="2xl" />
<CIcon name="cil-coffee" size="2xl" />
<CIcon name="cil-balance-scale" size="2xl" />
<CIcon name="cil-arrow-circle-top" size="2xl" />
<CIcon name="cil-border-bottom" size="2xl" />
<CIcon name="cil-clone" size="2xl" />
<CIcon name="cil-eyedropper" size="2xl" />
<CIcon name="cil-notes" size="2xl" />
<CIcon name="cil-door" size="2xl" />
<CIcon name="cil-drink" size="2xl" />
<CIcon name="cil-https" size="2xl" />
<CIcon name="cil-filter-square" size="2xl" />
<CIcon name="cil-tags" size="2xl" />
<CIcon name="cil-av-timer" size="2xl" />
<CIcon name="cil-terminal" size="2xl" />
<CIcon name="cil-contrast" size="2xl" />
<CIcon name="cil-arrow-thick-to-left" size="2xl" />
<CIcon name="cil-apps-settings" size="2xl" />

  </>
  )

}
const UserListFoo = () => {
  return <div>user list (foo)</div>
}
const UserListBar = () => {
  return <div>user list (bar)</div>
}

export const routes = [
  {
    path: '/users',
    name: "회원",
    exact: true,
    component: UserDashboard,
  },
  {
    path: '/users/list',
    name: "목록",
    exact: true,
    component: UserList,
  },
  {
    path: '/users/foo',
    name: "목록 (foo)",
    exact: true,
    component: UserListFoo,
  },
  {
    path: '/users/bar',
    name: "목록 (bar)",
    component: UserListBar,
  },
]
